lazyMageLoad.metadata:updateRevisionFromKeyword("$Revision: 689 $")

function lazyMageLoad.LoadMageLocalization(locale)

	lazyMageLocale.enUS.ACTION_TTS.amplifyMagic     = "Amplify Magic"
	lazyMageLocale.enUS.ACTION_TTS.arcanePower      = "Arcane Power"
	lazyMageLocale.enUS.ACTION_TTS.blastWave        = "Blast Wave"
	lazyMageLocale.enUS.ACTION_TTS.blink            = "Blink"
	lazyMageLocale.enUS.ACTION_TTS.blizzard         = "Blizzard"
	lazyMageLocale.enUS.ACTION_TTS.brilliance       = "Arcane Brilliance"
	lazyMageLocale.enUS.ACTION_TTS.coldSnap         = "Cold Snap"
	lazyMageLocale.enUS.ACTION_TTS.combustion       = "Combustion"
	lazyMageLocale.enUS.ACTION_TTS.coneCold         = "Cone of Cold"
	lazyMageLocale.enUS.ACTION_TTS.conjureAgate     = "Conjure Mana Agate"
	lazyMageLocale.enUS.ACTION_TTS.conjureCitrine   = "Conjure Mana Citrine"
	lazyMageLocale.enUS.ACTION_TTS.conjureFood      = "Conjure Food"
	lazyMageLocale.enUS.ACTION_TTS.conjureJade      = "Conjure Mana Jade"
	lazyMageLocale.enUS.ACTION_TTS.conjureRuby      = "Conjure Mana Ruby"
	lazyMageLocale.enUS.ACTION_TTS.conjureWater     = "Conjure Water"
	lazyMageLocale.enUS.ACTION_TTS.counter          = "Counterspell"
	lazyMageLocale.enUS.ACTION_TTS.dampenMagic      = "Dampen Magic"
	lazyMageLocale.enUS.ACTION_TTS.detectMagic      = "Detect Magic"
	lazyMageLocale.enUS.ACTION_TTS.evocation        = "Evocation"
	lazyMageLocale.enUS.ACTION_TTS.explosion        = "Arcane Explosion"
	lazyMageLocale.enUS.ACTION_TTS.fireball         = "Fireball"
	lazyMageLocale.enUS.ACTION_TTS.fireBlast        = "Fire Blast"
	lazyMageLocale.enUS.ACTION_TTS.fireWard         = "Fire Ward"
	lazyMageLocale.enUS.ACTION_TTS.flamestrike      = "Flamestrike"
	lazyMageLocale.enUS.ACTION_TTS.frostArmor       = "Frost Armor"
	lazyMageLocale.enUS.ACTION_TTS.frostbolt        = "Frostbolt"
	lazyMageLocale.enUS.ACTION_TTS.frostNova        = "Frost Nova"
	lazyMageLocale.enUS.ACTION_TTS.frostWard        = "Frost Ward"
	lazyMageLocale.enUS.ACTION_TTS.iceArmor         = "Ice Armor"
	lazyMageLocale.enUS.ACTION_TTS.iceBarrier       = "Ice Barrier"
	lazyMageLocale.enUS.ACTION_TTS.iceBlock         = "Ice Block"
	lazyMageLocale.enUS.ACTION_TTS.intellect        = "Arcane Intellect"
	lazyMageLocale.enUS.ACTION_TTS.mageArmor        = "Mage Armor"
	lazyMageLocale.enUS.ACTION_TTS.manaShield       = "Mana Shield"
	lazyMageLocale.enUS.ACTION_TTS.missiles         = "Arcane Missiles"
	lazyMageLocale.enUS.ACTION_TTS.pig              = "Polymorph: Pig"
	lazyMageLocale.enUS.ACTION_TTS.pom              = "Presence of Mind"
	lazyMageLocale.enUS.ACTION_TTS.pyroblast        = "Pyroblast"
	lazyMageLocale.enUS.ACTION_TTS.removeCurse      = "Remove Curse"
	lazyMageLocale.enUS.ACTION_TTS.scorch           = "Scorch"
	lazyMageLocale.enUS.ACTION_TTS.sheep            = "Polymorph"
	lazyMageLocale.enUS.ACTION_TTS.slowFall         = "Slow Fall"
	lazyMageLocale.enUS.ACTION_TTS.teleDarnassus    = "Teleport: Darnassus"
	lazyMageLocale.enUS.ACTION_TTS.teleIronforge    = "Teleport: Ironforge"
	lazyMageLocale.enUS.ACTION_TTS.teleOgrimmar     = "Teleport: Ogrimmar"
	lazyMageLocale.enUS.ACTION_TTS.teleStormwind    = "Teleport: Stormwind"
	lazyMageLocale.enUS.ACTION_TTS.teleThunderBluff = "Teleport: Thunder Bluff"
	lazyMageLocale.enUS.ACTION_TTS.teleUndercity    = "Teleport: Undercity"
	lazyMageLocale.enUS.ACTION_TTS.turtle           = "Polymorph: Turtle"
	lazyMageLocale.enUS.ACTION_TTS.portDarnassus    = "Portal: Darnassus"
	lazyMageLocale.enUS.ACTION_TTS.portIronforge    = "Portal: Ironforge"
	lazyMageLocale.enUS.ACTION_TTS.portOgrimmar     = "Portal: Ogrimmar"
	lazyMageLocale.enUS.ACTION_TTS.portStormwind    = "Portal: Stormwind"
	lazyMageLocale.enUS.ACTION_TTS.portThunderBluff = "Portal: Thunder Bluff"
	lazyMageLocale.enUS.ACTION_TTS.portUndercity    = "Portal: Undercity"
	lazyMageLocale.enUS.ACTION_TTS.askl             = "Arcane Rupture"
	lazyMageLocale.enUS.ACTION_TTS.asyd             = "Arcane Surge"

	-- LazyMage.lua
	MAGE_ADDON_LOADED = " loaded. Powered by "

	-- ParseMage.lua
	function lazyMage.CustomLocaleHelp() return [[<H2>Mage Criteria:</H2>]] end

	if (locale == "zhCN") then

		lazyMageLocale.zhCN.ACTION_TTS.amplifyMagic     = "魔法增效"
		lazyMageLocale.zhCN.ACTION_TTS.arcanePower      = "奥术强化"
		lazyMageLocale.zhCN.ACTION_TTS.blastWave        = "冲击波"
		lazyMageLocale.zhCN.ACTION_TTS.blink            = "闪现术"
		lazyMageLocale.zhCN.ACTION_TTS.blizzard         = "暴风雪"
		lazyMageLocale.zhCN.ACTION_TTS.brilliance       = "奥术光辉"
		lazyMageLocale.zhCN.ACTION_TTS.coldSnap         = "急速冷却"
		lazyMageLocale.zhCN.ACTION_TTS.combustion       = "燃烧"
		lazyMageLocale.zhCN.ACTION_TTS.coneCold         = "冰锥术"
		lazyMageLocale.zhCN.ACTION_TTS.conjureAgate     = "制造魔法玛瑙"
		lazyMageLocale.zhCN.ACTION_TTS.conjureCitrine   = "制造魔法黄水晶"
		lazyMageLocale.zhCN.ACTION_TTS.conjureFood      = "造食术"
		lazyMageLocale.zhCN.ACTION_TTS.conjureJade      = "制造魔法翡翠"
		lazyMageLocale.zhCN.ACTION_TTS.conjureRuby      = "制造魔法红宝石"
		lazyMageLocale.zhCN.ACTION_TTS.conjureWater     = "造水术"
		lazyMageLocale.zhCN.ACTION_TTS.counter          = "法术反制"
		lazyMageLocale.zhCN.ACTION_TTS.dampenMagic      = "魔法抑制"
		lazyMageLocale.zhCN.ACTION_TTS.detectMagic      = "侦测魔法"
		lazyMageLocale.zhCN.ACTION_TTS.evocation        = "唤醒"
		lazyMageLocale.zhCN.ACTION_TTS.explosion        = "魔爆术"
		lazyMageLocale.zhCN.ACTION_TTS.fireball         = "火球术"
		lazyMageLocale.zhCN.ACTION_TTS.fireBlast        = "火焰冲击"
		lazyMageLocale.zhCN.ACTION_TTS.fireWard         = "防护火焰结界"
		lazyMageLocale.zhCN.ACTION_TTS.flamestrike      = "烈焰风暴"
		lazyMageLocale.zhCN.ACTION_TTS.frostArmor       = "霜甲术"
		lazyMageLocale.zhCN.ACTION_TTS.frostbolt        = "寒冰箭"
		lazyMageLocale.zhCN.ACTION_TTS.frostNova        = "冰霜新星"
		lazyMageLocale.zhCN.ACTION_TTS.frostWard        = "防护冰霜结界"
		lazyMageLocale.zhCN.ACTION_TTS.iceArmor         = "冰甲术"
		lazyMageLocale.zhCN.ACTION_TTS.iceBarrier       = "寒冰护体"
		lazyMageLocale.zhCN.ACTION_TTS.iceBlock         = "寒冰屏障"
		lazyMageLocale.zhCN.ACTION_TTS.intellect        = "奥术智慧"
		lazyMageLocale.zhCN.ACTION_TTS.mageArmor        = "魔甲术"
		lazyMageLocale.zhCN.ACTION_TTS.manaShield       = "法力护盾"
		lazyMageLocale.zhCN.ACTION_TTS.missiles         = "奥术飞弹"
		lazyMageLocale.zhCN.ACTION_TTS.pig              = "变形术：猪"
		lazyMageLocale.zhCN.ACTION_TTS.pom              = "气定神闲"
		lazyMageLocale.zhCN.ACTION_TTS.pyroblast        = "炎爆术"
		lazyMageLocale.zhCN.ACTION_TTS.removeCurse      = "解除诅咒"
		lazyMageLocale.zhCN.ACTION_TTS.scorch           = "灼烧"
		lazyMageLocale.zhCN.ACTION_TTS.sheep            = "变形术"
		lazyMageLocale.zhCN.ACTION_TTS.slowFall         = "缓落术"
		lazyMageLocale.zhCN.ACTION_TTS.teleDarnassus    = "传送：达纳苏斯"
		lazyMageLocale.zhCN.ACTION_TTS.teleIronforge    = "传送：铁炉堡"
		lazyMageLocale.zhCN.ACTION_TTS.teleOgrimmar     = "传送：奥格瑞玛"
		lazyMageLocale.zhCN.ACTION_TTS.teleStormwind    = "传送：暴风城"
		lazyMageLocale.zhCN.ACTION_TTS.teleThunderBluff = "传送：雷霆崖"
		lazyMageLocale.zhCN.ACTION_TTS.teleUndercity    = "传送：幽暗城"
		lazyMageLocale.zhCN.ACTION_TTS.turtle           = "变形术：龟"
		lazyMageLocale.zhCN.ACTION_TTS.portDarnassus    = "传送门：达纳苏斯"
		lazyMageLocale.zhCN.ACTION_TTS.portIronforge    = "传送门：铁炉堡"
		lazyMageLocale.zhCN.ACTION_TTS.portOgrimmar     = "传送门：奥格瑞玛"
		lazyMageLocale.zhCN.ACTION_TTS.portStormwind    = "传送门：暴风城"
		lazyMageLocale.zhCN.ACTION_TTS.portThunderBluff = "传送门：雷霆崖"
		lazyMageLocale.zhCN.ACTION_TTS.portUndercity    = "传送门：幽暗城"
		lazyMageLocale.zhCN.ACTION_TTS.askl             = "奥术溃裂"
		lazyMageLocale.zhCN.ACTION_TTS.asyd             = "奥术涌动"

	end
end
