lazyWarriorLoad.metadata:updateRevisionFromKeyword("$Revision: 644 $")

function lazyWarriorLoad.LoadWarriorLocalization(locale)

	lazyWarriorLocale.enUS.ACTION_TTS.bloodrage         = "Bloodrage"
	lazyWarriorLocale.enUS.ACTION_TTS.charge            = "Charge"
	lazyWarriorLocale.enUS.ACTION_TTS.battleShout       = "Battle Shout"
	lazyWarriorLocale.enUS.ACTION_TTS.thunderClap       = "Thunder Clap"
	lazyWarriorLocale.enUS.ACTION_TTS.rend              = "Rend"
	lazyWarriorLocale.enUS.ACTION_TTS.hamstring         = "Hamstring"
	lazyWarriorLocale.enUS.ACTION_TTS.heroicStrike      = "Heroic Strike"
	lazyWarriorLocale.enUS.ACTION_TTS.sunder            = "Sunder Armor"
	lazyWarriorLocale.enUS.ACTION_TTS.overpower         = "Overpower"
	lazyWarriorLocale.enUS.ACTION_TTS.demoShout         = "Demoralizing Shout"
	lazyWarriorLocale.enUS.ACTION_TTS.revenge           = "Revenge"
	lazyWarriorLocale.enUS.ACTION_TTS.mockingBlow       = "Mocking Blow"
	lazyWarriorLocale.enUS.ACTION_TTS.shieldBlock       = "Shield Block"
	lazyWarriorLocale.enUS.ACTION_TTS.disarm            = "Disarm"
	lazyWarriorLocale.enUS.ACTION_TTS.cleave            = "Cleave"
	lazyWarriorLocale.enUS.ACTION_TTS.execute           = "Execute"
	lazyWarriorLocale.enUS.ACTION_TTS.deathWish         = "Death Wish"
	lazyWarriorLocale.enUS.ACTION_TTS.intercept         = "Intercept"
	lazyWarriorLocale.enUS.ACTION_TTS.intervene         = "Intervene"
	lazyWarriorLocale.enUS.ACTION_TTS.berserkerRage     = "Berserker Rage"
	lazyWarriorLocale.enUS.ACTION_TTS.whirlwind         = "Whirlwind"
	lazyWarriorLocale.enUS.ACTION_TTS.pummel            = "Pummel"
	lazyWarriorLocale.enUS.ACTION_TTS.bloodthirst       = "Bloodthirst"
	lazyWarriorLocale.enUS.ACTION_TTS.piercingHowl      = "Piercing Howl"
	lazyWarriorLocale.enUS.ACTION_TTS.taunt             = "Taunt"
	lazyWarriorLocale.enUS.ACTION_TTS.battle            = "Battle Stance"
	lazyWarriorLocale.enUS.ACTION_TTS.defensive         = "Defensive Stance"
	lazyWarriorLocale.enUS.ACTION_TTS.berserk           = "Berserker Stance"
	lazyWarriorLocale.enUS.ACTION_TTS.lastStand         = "Last Stand"
	lazyWarriorLocale.enUS.ACTION_TTS.shieldBash        = "Shield Bash"
	lazyWarriorLocale.enUS.ACTION_TTS.mortalStrike      = "Mortal Strike"
	lazyWarriorLocale.enUS.ACTION_TTS.shieldSlam        = "Shield Slam"
	lazyWarriorLocale.enUS.ACTION_TTS.sweepingStrikes   = "Sweeping Strikes"
	lazyWarriorLocale.enUS.ACTION_TTS.concussionBlow    = "Concussion Blow"
	lazyWarriorLocale.enUS.ACTION_TTS.challengingShout  = "Challenging Shout"
	lazyWarriorLocale.enUS.ACTION_TTS.intimidatingShout = "Intimidating Shout"
	lazyWarriorLocale.enUS.ACTION_TTS.recklessness      = "Recklessness"
	lazyWarriorLocale.enUS.ACTION_TTS.retaliation       = "Retaliation"
	lazyWarriorLocale.enUS.ACTION_TTS.shieldWall        = "Shield Wall"
	lazyWarriorLocale.enUS.ACTION_TTS.slam              = "Slam"
	lazyWarriorLocale.enUS.ACTION_TTS.fj                = "Counterattack"

	-- LazyWarrior.lua
	WARRIOR_ADDON_LOADED = " loaded. Powered by "

	-- ParseWarrior.lua
	WARRIOR_EARLY_BLOODTHIRST = "Early Bloodthirst! Kill shot!"
	WARRIOR_STANCE = "Stance: "
	WARRIOR_NOT_RECOGNISED = " not recognised."
	ITEM_SUBTYPE_SHIELDS = "Shields"
	JUDGE_SLAM = "Slam"

	function lazyWarrior.CustomLocaleHelp() return [[<H2>Warrior Criteria:</H2>]] end

	if (locale == "zhCN") then

		lazyWarriorLocale.zhCN.ACTION_TTS.bloodrage         = "血性狂暴"
		lazyWarriorLocale.zhCN.ACTION_TTS.charge            = "冲锋"
		lazyWarriorLocale.zhCN.ACTION_TTS.battleShout       = "战斗怒吼"
		lazyWarriorLocale.zhCN.ACTION_TTS.thunderClap       = "雷霆一击"
		lazyWarriorLocale.zhCN.ACTION_TTS.rend              = "撕裂"
		lazyWarriorLocale.zhCN.ACTION_TTS.hamstring         = "断筋"
		lazyWarriorLocale.zhCN.ACTION_TTS.heroicStrike      = "英勇打击"
		lazyWarriorLocale.zhCN.ACTION_TTS.sunder            = "破甲攻击"
		lazyWarriorLocale.zhCN.ACTION_TTS.overpower         = "压制"
		lazyWarriorLocale.zhCN.ACTION_TTS.demoShout         = "挫志怒吼"
		lazyWarriorLocale.zhCN.ACTION_TTS.revenge           = "复仇"
		lazyWarriorLocale.zhCN.ACTION_TTS.mockingBlow       = "惩戒痛击"
		lazyWarriorLocale.zhCN.ACTION_TTS.shieldBlock       = "盾牌格挡"
		lazyWarriorLocale.zhCN.ACTION_TTS.disarm            = "缴械"
		lazyWarriorLocale.zhCN.ACTION_TTS.cleave            = "顺劈斩"
		lazyWarriorLocale.zhCN.ACTION_TTS.execute           = "斩杀"
		lazyWarriorLocale.zhCN.ACTION_TTS.deathWish         = "死亡之愿"
		lazyWarriorLocale.zhCN.ACTION_TTS.intercept         = "拦截"
		lazyWarriorLocale.zhCN.ACTION_TTS.intervene         = "援护"
		lazyWarriorLocale.zhCN.ACTION_TTS.berserkerRage     = "狂暴之怒"
		lazyWarriorLocale.zhCN.ACTION_TTS.whirlwind         = "旋风斩"
		lazyWarriorLocale.zhCN.ACTION_TTS.pummel            = "拳击"
		lazyWarriorLocale.zhCN.ACTION_TTS.bloodthirst       = "嗜血"
		lazyWarriorLocale.zhCN.ACTION_TTS.piercingHowl      = "刺耳怒吼"
		lazyWarriorLocale.zhCN.ACTION_TTS.taunt             = "嘲讽"
		lazyWarriorLocale.zhCN.ACTION_TTS.battle            = "战斗姿态"
		lazyWarriorLocale.zhCN.ACTION_TTS.defensive         = "防御姿态"
		lazyWarriorLocale.zhCN.ACTION_TTS.berserk           = "狂暴姿态"
		lazyWarriorLocale.zhCN.ACTION_TTS.lastStand         = "破釜沉舟"
		lazyWarriorLocale.zhCN.ACTION_TTS.shieldBash        = "盾击"
		lazyWarriorLocale.zhCN.ACTION_TTS.mortalStrike      = "致死打击"
		lazyWarriorLocale.zhCN.ACTION_TTS.shieldSlam        = "盾牌猛击"
		lazyWarriorLocale.zhCN.ACTION_TTS.sweepingStrikes   = "横扫攻击"
		lazyWarriorLocale.zhCN.ACTION_TTS.concussionBlow    = "震荡猛击"
		lazyWarriorLocale.zhCN.ACTION_TTS.challengingShout  = "挑战怒吼"
		lazyWarriorLocale.zhCN.ACTION_TTS.intimidatingShout = "破胆怒吼"
		lazyWarriorLocale.zhCN.ACTION_TTS.recklessness      = "鲁莽"
		lazyWarriorLocale.zhCN.ACTION_TTS.retaliation       = "反击风暴"
		lazyWarriorLocale.zhCN.ACTION_TTS.shieldWall        = "盾墙"
		lazyWarriorLocale.zhCN.ACTION_TTS.slam              = "猛击"
		lazyWarriorLocale.zhCN.ACTION_TTS.fj                = "反击"

		-- ParseWarrior.lua
		WARRIOR_STANCE = "姿态："
		ITEM_SUBTYPE_SHIELDS = "盾牌"
		JUDGE_SLAM = "猛击"
	end
end
