lazyWarlockLoad.metadata:updateRevisionFromKeyword("$Revision: 534 $")

function lazyWarlockLoad.LoadWarlockLocalization(locale)

	lazyWarlockLocale.enUS.ACTION_TTS.amplifyCurse        = "Amplify Curse"
	lazyWarlockLocale.enUS.ACTION_TTS.banish              = "Banish"
	lazyWarlockLocale.enUS.ACTION_TTS.conflagrate         = "Conflagrate"
	lazyWarlockLocale.enUS.ACTION_TTS.corruption          = "Corruption"

	lazyWarlockLocale.enUS.ACTION_TTS.createFel           = "Create Felstone"
	lazyWarlockLocale.enUS.ACTION_TTS.createFire          = "Create Firestone"
	lazyWarlockLocale.enUS.ACTION_TTS.createWrath         = "Create Wrathstone"

	lazyWarlockLocale.enUS.ACTION_TTS.createGreaterHealth = "Create Healthstone (Greater)"
	lazyWarlockLocale.enUS.ACTION_TTS.createHealth        = "Create Healthstone"
	lazyWarlockLocale.enUS.ACTION_TTS.createLesserHealth  = "Create Healthstone (Lesser)"
	lazyWarlockLocale.enUS.ACTION_TTS.createMajorHealth   = "Create Healthstone (Major)"
	lazyWarlockLocale.enUS.ACTION_TTS.createMinorHealth   = "Create Healthstone (Minor)"

	lazyWarlockLocale.enUS.ACTION_TTS.createGreaterSoul   = "Create Soulstone (Greater)"
	lazyWarlockLocale.enUS.ACTION_TTS.createLesserSoul    = "Create Soulstone (Lesser)"
	lazyWarlockLocale.enUS.ACTION_TTS.createMajorSoul     = "Create Soulstone (Major)"
	lazyWarlockLocale.enUS.ACTION_TTS.createMinorSoul     = "Create Soulstone (Minor)"
	lazyWarlockLocale.enUS.ACTION_TTS.createSoul          = "Create Soulstone"

	lazyWarlockLocale.enUS.ACTION_TTS.curseAgony          = "Curse of Agony"
	lazyWarlockLocale.enUS.ACTION_TTS.curseDoom           = "Curse of Doom"
	lazyWarlockLocale.enUS.ACTION_TTS.curseElements       = "Curse of Elements"
	lazyWarlockLocale.enUS.ACTION_TTS.curseExhaustion     = "Curse of Exhaustion"
	lazyWarlockLocale.enUS.ACTION_TTS.curseReckless       = "Curse of Recklessness"
	lazyWarlockLocale.enUS.ACTION_TTS.curseShadow         = "Curse of Shadow"
	lazyWarlockLocale.enUS.ACTION_TTS.curseTongues        = "Curse of Tongues"
	lazyWarlockLocale.enUS.ACTION_TTS.curseWeakness       = "Curse of Weakness"
	lazyWarlockLocale.enUS.ACTION_TTS.darkPact            = "Dark Pact"
	lazyWarlockLocale.enUS.ACTION_TTS.deathCoil           = "Death Coil"
	lazyWarlockLocale.enUS.ACTION_TTS.demonArmor          = "Demon Armor"
	lazyWarlockLocale.enUS.ACTION_TTS.demonicSacrifice    = "Demonic Sacrifice"
	lazyWarlockLocale.enUS.ACTION_TTS.demonSkin           = "Demon Skin"
	lazyWarlockLocale.enUS.ACTION_TTS.detectGreaterInvis  = "Detect Greater Invisibility"
	lazyWarlockLocale.enUS.ACTION_TTS.detectInvis         = "Detect Invisibility"
	lazyWarlockLocale.enUS.ACTION_TTS.detectLesserInvis   = "Detect Lesser Invisibility"
	lazyWarlockLocale.enUS.ACTION_TTS.drainLife           = "Drain Life"
	lazyWarlockLocale.enUS.ACTION_TTS.drainMana           = "Drain Mana"
	lazyWarlockLocale.enUS.ACTION_TTS.drainSoul           = "Drain Soul"
	lazyWarlockLocale.enUS.ACTION_TTS.enslave             = "Enslave Demon"
	lazyWarlockLocale.enUS.ACTION_TTS.fear                = "Fear"
	lazyWarlockLocale.enUS.ACTION_TTS.felDomination       = "Fel Domination"
	lazyWarlockLocale.enUS.ACTION_TTS.funnel              = "Health Funnel"
	lazyWarlockLocale.enUS.ACTION_TTS.hellfire            = "Hellfire"
	lazyWarlockLocale.enUS.ACTION_TTS.howl                = "Howl of Terror"
	lazyWarlockLocale.enUS.ACTION_TTS.immolate            = "Immolate"
	lazyWarlockLocale.enUS.ACTION_TTS.inferno	          = "Inferno"
	lazyWarlockLocale.enUS.ACTION_TTS.lifeTap             = "Life Tap"
	lazyWarlockLocale.enUS.ACTION_TTS.pact                = "Dark Pact"
	lazyWarlockLocale.enUS.ACTION_TTS.pain                = "Searing Pain"
	lazyWarlockLocale.enUS.ACTION_TTS.rainFire            = "Rain of Fire"
	lazyWarlockLocale.enUS.ACTION_TTS.senseDemons         = "Sense Demons"
	lazyWarlockLocale.enUS.ACTION_TTS.shadowBolt          = "Shadow Bolt"
	lazyWarlockLocale.enUS.ACTION_TTS.shadowburn          = "Shadowburn"
	lazyWarlockLocale.enUS.ACTION_TTS.shadowWard          = "Shadow Ward"
	lazyWarlockLocale.enUS.ACTION_TTS.siphon              = "Siphon Life"
	lazyWarlockLocale.enUS.ACTION_TTS.soulFire            = "Soul Fire"
	lazyWarlockLocale.enUS.ACTION_TTS.soulLink            = "Soul Link"
	lazyWarlockLocale.enUS.ACTION_TTS.summonDread         = "Summon Dreadsteed"
	lazyWarlockLocale.enUS.ACTION_TTS.spellLock           = "Spell lock"
	lazyWarlockLocale.enUS.ACTION_TTS.summonFel           = "Summon Felhunter"
	lazyWarlockLocale.enUS.ACTION_TTS.summonImp           = "Summon Imp"
	lazyWarlockLocale.enUS.ACTION_TTS.summonSteed         = "Summon Felsteed"
	lazyWarlockLocale.enUS.ACTION_TTS.summonSuc           = "Summon Succubus"
	lazyWarlockLocale.enUS.ACTION_TTS.summonVW            = "Summon Voidwalker"
	lazyWarlockLocale.enUS.ACTION_TTS.aysg                = "Dark Harvest"

	lazyWarlockLocale.enUS.ACTION_TTS.bloodPact           = "Blood Pact"
	lazyWarlockLocale.enUS.ACTION_TTS.firebolt            = "Firebolt"
	lazyWarlockLocale.enUS.ACTION_TTS.phaseShift          = "Phase Shift"
	lazyWarlockLocale.enUS.ACTION_TTS.fireShield          = "Fire Shield"

	lazyWarlockLocale.enUS.ACTION_TTS.consumeShadows      = "Consume Shadows"
	lazyWarlockLocale.enUS.ACTION_TTS.sacrifice           = "Sacrifice"
	lazyWarlockLocale.enUS.ACTION_TTS.suffering           = "Suffering"
	lazyWarlockLocale.enUS.ACTION_TTS.torment             = "Torment"

	lazyWarlockLocale.enUS.ACTION_TTS.lashPain            = "Lash of Pain"
	lazyWarlockLocale.enUS.ACTION_TTS.lesserInvisibility  = "Lesser Invisibility"
	lazyWarlockLocale.enUS.ACTION_TTS.seduction           = "Seduction"
	lazyWarlockLocale.enUS.ACTION_TTS.soothingKiss        = "Soothing Kiss"

	lazyWarlockLocale.enUS.ACTION_TTS.taintedBlood        = "Tainted Blood"
	lazyWarlockLocale.enUS.ACTION_TTS.spellLock           = "Spell Lock"
	lazyWarlockLocale.enUS.ACTION_TTS.devourMagic         = "Devour Magic"
	lazyWarlockLocale.enUS.ACTION_TTS.paranoia            = "Paranoia"

	lazyWarlockLocale.enUS.HEALTHSTONE                    = "Healthstone"
	lazyWarlockLocale.enUS.SOULSTONE                      = "Soulstone"
	lazyWarlockLocale.enUS.FIRESTONE                      = "Firestone"

	-- LazyWarlock.lua
	WARLOCK_ADDON_LOADED = " loaded. Powered by "

	-- ParseWarlock.lua
	WARLOCK_RANK = "Rank "
	WARLOCK_CONFLAG_NOT_SUPPORT = " of Conflagrate is not supported by LazyScript! Please report this error to the lazydevs team."
	WARLOCK_CONFLAG_DAMAGE = "IsLastConflagrateChance: Conflagrate damage="
	WARLOCK_OFFHAND_CONTAINS = "Offhand contains: "


	function lazyWarlock.CustomLocaleHelp() return [[<H2>Warlock Criteria:</H2>]] end

	if (locale == "zhCN") then

		lazyWarlockLocale.zhCN.ACTION_TTS.amplifyCurse        = "诅咒增幅"
		lazyWarlockLocale.zhCN.ACTION_TTS.banish              = "放逐术"
		lazyWarlockLocale.zhCN.ACTION_TTS.conflagrate         = "燃烧"
		lazyWarlockLocale.zhCN.ACTION_TTS.corruption          = "腐蚀术"
		lazyWarlockLocale.zhCN.ACTION_TTS.createFel           = "制造恶魔石"
		lazyWarlockLocale.zhCN.ACTION_TTS.createFire          = "制造火焰石"
		lazyWarlockLocale.zhCN.ACTION_TTS.createWrath         = "制造愤怒石"
		lazyWarlockLocale.zhCN.ACTION_TTS.createGreaterHealth = "制造强效治疗石"
		lazyWarlockLocale.zhCN.ACTION_TTS.createHealth        = "制造治疗石"
		lazyWarlockLocale.zhCN.ACTION_TTS.createLesserHealth  = "制造次级治疗石"
		lazyWarlockLocale.zhCN.ACTION_TTS.createMajorHealth   = "制造特效治疗石"
		lazyWarlockLocale.zhCN.ACTION_TTS.createMinorHealth   = "制造初级治疗石"
		lazyWarlockLocale.zhCN.ACTION_TTS.createGreaterSoul   = "制造强效灵魂石"
		lazyWarlockLocale.zhCN.ACTION_TTS.createLesserSoul    = "制造次级灵魂石"
		lazyWarlockLocale.zhCN.ACTION_TTS.createMajorSoul     = "制造特效灵魂石"
		lazyWarlockLocale.zhCN.ACTION_TTS.createMinorSoul     = "制造初级灵魂石"
		lazyWarlockLocale.zhCN.ACTION_TTS.createSoul          = "制造灵魂石"
		lazyWarlockLocale.zhCN.ACTION_TTS.curseAgony          = "痛苦诅咒"
		lazyWarlockLocale.zhCN.ACTION_TTS.curseDoom           = "厄运诅咒"
		lazyWarlockLocale.zhCN.ACTION_TTS.curseElements       = "元素诅咒"
		lazyWarlockLocale.zhCN.ACTION_TTS.curseExhaustion     = "疲劳诅咒"
		lazyWarlockLocale.zhCN.ACTION_TTS.curseReckless       = "鲁莽诅咒"
		lazyWarlockLocale.zhCN.ACTION_TTS.curseShadow         = "暗影诅咒"
		lazyWarlockLocale.zhCN.ACTION_TTS.curseTongues        = "语言诅咒"
		lazyWarlockLocale.zhCN.ACTION_TTS.curseWeakness       = "虚弱诅咒"
		lazyWarlockLocale.zhCN.ACTION_TTS.darkPact            = "黑暗契约"
		lazyWarlockLocale.zhCN.ACTION_TTS.deathCoil           = "死亡缠绕"
		lazyWarlockLocale.zhCN.ACTION_TTS.demonArmor          = "魔甲术"
		lazyWarlockLocale.zhCN.ACTION_TTS.demonicSacrifice    = "恶魔牺牲"
		lazyWarlockLocale.zhCN.ACTION_TTS.demonSkin           = "恶魔皮肤"
		lazyWarlockLocale.zhCN.ACTION_TTS.detectGreaterInvis  = "侦测强效隐形"
		lazyWarlockLocale.zhCN.ACTION_TTS.detectInvis         = "侦测隐形"
		lazyWarlockLocale.zhCN.ACTION_TTS.detectLesserInvis   = "侦测次级隐形"
		lazyWarlockLocale.zhCN.ACTION_TTS.drainLife           = "吸取生命"
		lazyWarlockLocale.zhCN.ACTION_TTS.drainMana           = "吸取法力"
		lazyWarlockLocale.zhCN.ACTION_TTS.drainSoul           = "吸取灵魂"
		lazyWarlockLocale.zhCN.ACTION_TTS.enslave             = "奴役恶魔"
		lazyWarlockLocale.zhCN.ACTION_TTS.fear                = "恐惧术"
		lazyWarlockLocale.zhCN.ACTION_TTS.felDomination       = "恶魔支配"
		lazyWarlockLocale.zhCN.ACTION_TTS.funnel              = "生命通道"
		lazyWarlockLocale.zhCN.ACTION_TTS.aysg                = "暗影收割"
		lazyWarlockLocale.zhCN.ACTION_TTS.hellfire            = "地狱烈焰"
		lazyWarlockLocale.zhCN.ACTION_TTS.howl                = "恐惧嚎叫"
		lazyWarlockLocale.zhCN.ACTION_TTS.immolate            = "献祭"
		lazyWarlockLocale.zhCN.ACTION_TTS.inferno	          = "地狱火"
		lazyWarlockLocale.zhCN.ACTION_TTS.lifeTap             = "生命分流"
		lazyWarlockLocale.zhCN.ACTION_TTS.pact                = "黑暗契约"
		lazyWarlockLocale.zhCN.ACTION_TTS.pain                = "灼热之痛"
		lazyWarlockLocale.zhCN.ACTION_TTS.rainFire            = "火焰之雨"
		lazyWarlockLocale.zhCN.ACTION_TTS.senseDemons         = "感知恶魔"
		lazyWarlockLocale.zhCN.ACTION_TTS.shadowBolt          = "暗影箭"
		lazyWarlockLocale.zhCN.ACTION_TTS.shadowburn          = "暗影灼烧"
		lazyWarlockLocale.zhCN.ACTION_TTS.shadowWard          = "防护暗影结界"
		lazyWarlockLocale.zhCN.ACTION_TTS.siphon              = "生命虹吸"
		lazyWarlockLocale.zhCN.ACTION_TTS.soulFire            = "灵魂之火"
		lazyWarlockLocale.zhCN.ACTION_TTS.soulLink            = "灵魂链接"
		lazyWarlockLocale.zhCN.ACTION_TTS.summonDread         = "召唤恐惧战马"
		lazyWarlockLocale.zhCN.ACTION_TTS.spellLock           = "法术封锁"
		lazyWarlockLocale.zhCN.ACTION_TTS.summonFel           = "召唤地狱猎犬"
		lazyWarlockLocale.zhCN.ACTION_TTS.summonImp           = "召唤小鬼"
		lazyWarlockLocale.zhCN.ACTION_TTS.summonSteed         = "召唤地狱战马"
		lazyWarlockLocale.zhCN.ACTION_TTS.summonSuc           = "召唤魅魔"
		lazyWarlockLocale.zhCN.ACTION_TTS.summonVW            = "召唤虚空行者"
		lazyWarlockLocale.zhCN.ACTION_TTS.bloodPact           = "血之契印"
		lazyWarlockLocale.zhCN.ACTION_TTS.firebolt            = "火焰箭"
		lazyWarlockLocale.zhCN.ACTION_TTS.phaseShift          = "相位变换"
		lazyWarlockLocale.zhCN.ACTION_TTS.fireShield          = "火焰之盾"
		lazyWarlockLocale.zhCN.ACTION_TTS.consumeShadows      = "吞噬暗影"
		lazyWarlockLocale.zhCN.ACTION_TTS.sacrifice           = "牺牲"
		lazyWarlockLocale.zhCN.ACTION_TTS.suffering           = "受难"
		lazyWarlockLocale.zhCN.ACTION_TTS.torment             = "折磨"
		lazyWarlockLocale.zhCN.ACTION_TTS.lashPain            = "剧痛鞭笞"
		lazyWarlockLocale.zhCN.ACTION_TTS.lesserInvisibility  = "次级隐形术"
		lazyWarlockLocale.zhCN.ACTION_TTS.seduction           = "诱惑"
		lazyWarlockLocale.zhCN.ACTION_TTS.soothingKiss        = "安抚之吻"
		lazyWarlockLocale.zhCN.ACTION_TTS.taintedBlood        = "腐坏之血"
		lazyWarlockLocale.zhCN.ACTION_TTS.spellLock           = "法术封锁"
		lazyWarlockLocale.zhCN.ACTION_TTS.devourMagic         = "吞噬魔法"
		lazyWarlockLocale.zhCN.ACTION_TTS.paranoia            = "多疑"
		lazyWarlockLocale.zhCN.HEALTHSTONE                    = "治疗石"
		lazyWarlockLocale.zhCN.SOULSTONE                      = "灵魂石"
		lazyWarlockLocale.zhCN.FIRESTONE                      = "火焰石"

	end
end
