lazyPriestLoad.metadata:updateRevisionFromKeyword("$Revision: 308 $")

function lazyPriestLoad.LoadPriestLocalization(locale)

	lazyPriestLocale.enUS.ACTION_TTS.abolishDisease		= "Abolish Disease"
	lazyPriestLocale.enUS.ACTION_TTS.cureDisease		= "Cure Disease"
	lazyPriestLocale.enUS.ACTION_TTS.desperatePrayer	= "Desperate Prayer"
	lazyPriestLocale.enUS.ACTION_TTS.devouringPlague	= "Devouring Plague"
	lazyPriestLocale.enUS.ACTION_TTS.dispelMagic		= "Dispel Magic"
	lazyPriestLocale.enUS.ACTION_TTS.divineSpirit		= "Divine Spirit"
	lazyPriestLocale.enUS.ACTION_TTS.elunesGrace		= "Elune's Grace"
	lazyPriestLocale.enUS.ACTION_TTS.fade				= "Fade"
	lazyPriestLocale.enUS.ACTION_TTS.fearWard			= "Fear Ward"
	lazyPriestLocale.enUS.ACTION_TTS.feedback			= "Feedback"
	lazyPriestLocale.enUS.ACTION_TTS.flashHeal			= "Flash Heal"
	lazyPriestLocale.enUS.ACTION_TTS.greaterHeal		= "Greater Heal"
	lazyPriestLocale.enUS.ACTION_TTS.heal				= "Heal"
	lazyPriestLocale.enUS.ACTION_TTS.hexWeakness		= "Hex of Weakness"
	lazyPriestLocale.enUS.ACTION_TTS.holyFire			= "Holy Fire"
	lazyPriestLocale.enUS.ACTION_TTS.holyNova			= "Holy Nova"
	lazyPriestLocale.enUS.ACTION_TTS.innerFire			= "Inner Fire"
	lazyPriestLocale.enUS.ACTION_TTS.innerFocus			= "Inner Focus"
	lazyPriestLocale.enUS.ACTION_TTS.lesserHeal			= "Lesser Heal"
	lazyPriestLocale.enUS.ACTION_TTS.levitate			= "Levitate"
	lazyPriestLocale.enUS.ACTION_TTS.lightwell			= "Lightwell"
	lazyPriestLocale.enUS.ACTION_TTS.lightwellRenew		= "Lightwell Renew"
	lazyPriestLocale.enUS.ACTION_TTS.manaBurn			= "Mana Burn"
	lazyPriestLocale.enUS.ACTION_TTS.mindBlast			= "Mind Blast"
	lazyPriestLocale.enUS.ACTION_TTS.mindControl		= "Mind Control"
	lazyPriestLocale.enUS.ACTION_TTS.mindFlay			= "Mind Flay"
	lazyPriestLocale.enUS.ACTION_TTS.mindSoothe			= "Mind Soothe"
	lazyPriestLocale.enUS.ACTION_TTS.mindVision			= "Mind Vision"
	lazyPriestLocale.enUS.ACTION_TTS.powerInfusion		= "Power Infusion"
	lazyPriestLocale.enUS.ACTION_TTS.pwf				= "Power Word: Fortitude"
	lazyPriestLocale.enUS.ACTION_TTS.pws				= "Power Word: Shield"
	lazyPriestLocale.enUS.ACTION_TTS.prf				= "Prayer of Fortitude"
	lazyPriestLocale.enUS.ACTION_TTS.prh				= "Prayer of Healing"
	lazyPriestLocale.enUS.ACTION_TTS.prsp				= "Prayer of Shadow Protection"
	lazyPriestLocale.enUS.ACTION_TTS.prs				= "Prayer of Spirit"
	lazyPriestLocale.enUS.ACTION_TTS.psychicScream		= "Psychic Scream"
	lazyPriestLocale.enUS.ACTION_TTS.renew				= "Renew"
	lazyPriestLocale.enUS.ACTION_TTS.resurrection		= "Resurrection"
	lazyPriestLocale.enUS.ACTION_TTS.shackleUndead		= "Shackle Undead"
	lazyPriestLocale.enUS.ACTION_TTS.shadowProtection	= "Shadow Protection"
	lazyPriestLocale.enUS.ACTION_TTS.swp				= "Shadow Word: Pain"
	lazyPriestLocale.enUS.ACTION_TTS.shadowform			= "Shadowform"
	lazyPriestLocale.enUS.ACTION_TTS.shadowguard		= "Shadowguard"
	lazyPriestLocale.enUS.ACTION_TTS.shadowmend			= "Shadowmend"		--暗影治疗，需在游戏中确认
	lazyPriestLocale.enUS.ACTION_TTS.silence			= "Silence"
	lazyPriestLocale.enUS.ACTION_TTS.smite				= "Smite"
	lazyPriestLocale.enUS.ACTION_TTS.starshards			= "Starshards"
	lazyPriestLocale.enUS.ACTION_TTS.tkjc				= "Pain Spike"
	lazyPriestLocale.enUS.ACTION_TTS.touchWeakness		= "Touch of Weakness"
	lazyPriestLocale.enUS.ACTION_TTS.vampiricEmbrace	= "Vampiric Embrace"
	lazyPriestLocale.enUS.ACTION_TTS.qf					= "Enlighten"
	lazyPriestLocale.enUS.ACTION_TTS.zf					= "Chastise"
	lazyPriestLocale.enUS.ACTION_TTS.afd				= "Avatar"


	-- LazyPriest.lua
	PRIEST_ADDON_LOADED = " loaded. Powered by "

	-- ParsePriest.lua
	function lazyPriest.CustomLocaleHelp() return [[<H2>Priest Criteria:</H2>]] end

	if (locale == "zhCN") then

		lazyPriestLocale.zhCN.ACTION_TTS.abolishDisease		= "驱除疾病"
		lazyPriestLocale.zhCN.ACTION_TTS.cureDisease		= "祛病术"
		lazyPriestLocale.zhCN.ACTION_TTS.desperatePrayer	= "绝望祷言"
		lazyPriestLocale.zhCN.ACTION_TTS.devouringPlague	= "噬灵瘟疫"
		lazyPriestLocale.zhCN.ACTION_TTS.dispelMagic		= "驱散魔法"
		lazyPriestLocale.zhCN.ACTION_TTS.divineSpirit		= "神圣之灵"
		lazyPriestLocale.zhCN.ACTION_TTS.elunesGrace		= "艾露恩的赐福"
		lazyPriestLocale.zhCN.ACTION_TTS.fade				= "渐隐术"
		lazyPriestLocale.zhCN.ACTION_TTS.fearWard			= "防护恐惧结界"
		lazyPriestLocale.zhCN.ACTION_TTS.feedback			= "回馈"
		lazyPriestLocale.zhCN.ACTION_TTS.flashHeal			= "快速治疗"
		lazyPriestLocale.zhCN.ACTION_TTS.greaterHeal		= "强效治疗术"
		lazyPriestLocale.zhCN.ACTION_TTS.heal				= "治疗术"
		lazyPriestLocale.zhCN.ACTION_TTS.hexWeakness		= "虚弱妖术"
		lazyPriestLocale.zhCN.ACTION_TTS.holyFire			= "神圣之火"
		lazyPriestLocale.zhCN.ACTION_TTS.holyNova			= "神圣新星"
		lazyPriestLocale.zhCN.ACTION_TTS.innerFire			= "心灵之火"
		lazyPriestLocale.zhCN.ACTION_TTS.innerFocus			= "心灵专注"
		lazyPriestLocale.zhCN.ACTION_TTS.lesserHeal			= "次级治疗术"
		lazyPriestLocale.zhCN.ACTION_TTS.levitate			= "漂浮术"
		lazyPriestLocale.zhCN.ACTION_TTS.lightwell			= "光明之泉"
		lazyPriestLocale.zhCN.ACTION_TTS.lightwellRenew		= "光明之泉回复"
		lazyPriestLocale.zhCN.ACTION_TTS.manaBurn			= "法力燃烧"
		lazyPriestLocale.zhCN.ACTION_TTS.mindBlast			= "心灵震爆"
		lazyPriestLocale.zhCN.ACTION_TTS.mindControl		= "精神控制"
		lazyPriestLocale.zhCN.ACTION_TTS.mindFlay			= "精神鞭笞"
		lazyPriestLocale.zhCN.ACTION_TTS.mindSoothe			= "安抚心灵"
		lazyPriestLocale.zhCN.ACTION_TTS.mindVision			= "心灵视界"
		lazyPriestLocale.zhCN.ACTION_TTS.powerInfusion		= "能量灌注"
		lazyPriestLocale.zhCN.ACTION_TTS.pwf				= "真言术：韧"
		lazyPriestLocale.zhCN.ACTION_TTS.pws				= "真言术：盾"
		lazyPriestLocale.zhCN.ACTION_TTS.prf				= "坚韧祷言"
		lazyPriestLocale.zhCN.ACTION_TTS.prh				= "治疗祷言"
		lazyPriestLocale.zhCN.ACTION_TTS.prsp				= "暗影防护祷言"
		lazyPriestLocale.zhCN.ACTION_TTS.prs				= "精神祷言"
		lazyPriestLocale.zhCN.ACTION_TTS.psychicScream		= "心灵尖啸"
		lazyPriestLocale.zhCN.ACTION_TTS.renew				= "恢复"
		lazyPriestLocale.zhCN.ACTION_TTS.resurrection		= "复活术"
		lazyPriestLocale.zhCN.ACTION_TTS.shackleUndead		= "束缚亡灵"
		lazyPriestLocale.zhCN.ACTION_TTS.shadowProtection	= "防护暗影"
		lazyPriestLocale.zhCN.ACTION_TTS.swp				= "暗言术：痛"
		lazyPriestLocale.zhCN.ACTION_TTS.shadowform			= "暗影形态"
		lazyPriestLocale.zhCN.ACTION_TTS.shadowguard		= "暗影守卫"
		lazyPriestLocale.zhCN.ACTION_TTS.shadowmend			= "暗影治疗"
		lazyPriestLocale.zhCN.ACTION_TTS.silence			= "沉默"
		lazyPriestLocale.zhCN.ACTION_TTS.smite				= "惩击"
		lazyPriestLocale.zhCN.ACTION_TTS.starshards			= "星辰碎片"
		lazyPriestLocale.zhCN.ACTION_TTS.tkjc				= "痛苦尖刺"
		lazyPriestLocale.zhCN.ACTION_TTS.touchWeakness		= "虚弱之触"
		lazyPriestLocale.zhCN.ACTION_TTS.vampiricEmbrace	= "吸血鬼的拥抱"
		lazyPriestLocale.zhCN.ACTION_TTS.qf					= "启发"
		lazyPriestLocale.zhCN.ACTION_TTS.zf					= "责罚"
		lazyPriestLocale.zhCN.ACTION_TTS.afd				= "阿凡达"

	end
end
