W112_HOTPROBE_PAYLOAD_VERSION = (W112_HOTPROBE_PAYLOAD_VERSION or 0) + 1
if DEFAULT_CHAT_FRAME then
    DEFAULT_CHAT_FRAME:AddMessage("|cff66ff66[W112HotProbe]|r live payload applied #" .. W112_HOTPROBE_PAYLOAD_VERSION)
end
