from __future__ import annotations

import argparse
import csv
from pathlib import Path


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument('--cache-csv', required=True)
    ap.add_argument('--output-rs', required=True)
    args = ap.parse_args()

    cache_path = Path(args.cache_csv)
    output_path = Path(args.output_rs)

    rows: list[tuple[int, int, str]] = []
    with cache_path.open('r', encoding='utf-8-sig', newline='') as f:
        for row in csv.DictReader(f):
            try:
                item_id = int(row['item_id'])
                disenchant_id = int(row['disenchant_id'])
                source = (row.get('source') or 'SeedLegacy').strip() or 'SeedLegacy'
            except Exception as exc:
                raise SystemExit(f'invalid cache row {row!r}: {exc}')
            if item_id <= 0 or disenchant_id < 0:
                raise SystemExit(f'invalid cache values item_id={item_id} disenchant_id={disenchant_id}')
            rows.append((item_id, disenchant_id, source))

    dedup: dict[int, tuple[int, str]] = {}
    for item_id, disenchant_id, source in rows:
        old = dedup.get(item_id)
        if old is not None and old[0] != disenchant_id:
            raise SystemExit(
                f'conflicting cache entries item_id={item_id}: {old[0]} vs {disenchant_id}'
            )
        if old is None:
            dedup[item_id] = (disenchant_id, source)

    # Permanent regressions from the real project history.
    for blocked in (20406, 20407, 20408):
        if dedup.get(blocked, (-1, ''))[0] != 0:
            raise SystemExit(f'expected regression item {blocked} to have DisenchantID=0')
    if dedup.get(41316, (0, ''))[0] <= 0:
        raise SystemExit('expected known-positive item 41316 to have DisenchantID>0')

    output_path.parent.mkdir(parents=True, exist_ok=True)
    with output_path.open('w', encoding='utf-8', newline='\n') as f:
        f.write('// AUTO-GENERATED by poc08_de_cache_to_rust.py. DO NOT EDIT.\n')
        f.write('// Unknown item IDs intentionally return None and fail closed for DE.\n')
        f.write('fn poc08_exact_disenchant_id(item_id: u32) -> Option<u32> {\n')
        f.write('    match item_id {\n')
        for item_id in sorted(dedup):
            f.write(f'        {item_id} => Some({dedup[item_id][0]}),\n')
        f.write('        _ => None,\n')
        f.write('    }\n')
        f.write('}\n\n')
        f.write('fn poc08_exact_disenchant_source(item_id: u32) -> Option<&\'static str> {\n')
        f.write('    match item_id {\n')
        for item_id in sorted(dedup):
            source = dedup[item_id][1].replace('\\', '\\\\').replace('"', '\\"')
            f.write(f'        {item_id} => Some("{source}"),\n')
        f.write('        _ => None,\n')
        f.write('    }\n')
        f.write('}\n\n')
        f.write(f'const POC08_DE_CACHE_ENTRIES: usize = {len(dedup)};\n')

    zero = sum(1 for value, _ in dedup.values() if value == 0)
    positive = len(dedup) - zero
    source_counts: dict[str, int] = {}
    for _, source in dedup.values():
        source_counts[source] = source_counts.get(source, 0) + 1
    print(
        f'[POC08-DE-CACHE] PASS entries={len(dedup)} positive={positive} zero={zero} '
        f'sources={source_counts} output={output_path}'
    )
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
