from __future__ import annotations

import argparse
import csv
from pathlib import Path

VALID_SOURCES = {'OctoWow', 'CapyDB', 'SeedLegacy'}


def confidence_for(source: str) -> int:
    # Confidence scale:
    #   3 = authoritative / empirically validated (reserved; no current web source qualifies)
    #   2 = server-adjacent reference (Octo web DB)
    #   1 = external / legacy reference (CapyDB, SeedLegacy)
    #   0 = unknown
    # Octo's own forum has documented web-DB vs in-game discrepancies, so merely
    # being hosted on octowow.st must not authorize a future DE mutation.
    if source == 'OctoWow':
        return 2
    if source in {'CapyDB', 'SeedLegacy'}:
        return 1
    return 0


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument('--cache-csv', required=True)
    ap.add_argument('--output-rs', required=True)
    args = ap.parse_args()

    rows: list[tuple[int, int, str]] = []
    with Path(args.cache_csv).open('r', encoding='utf-8-sig', newline='') as f:
        for row in csv.DictReader(f):
            try:
                item_id = int(row['item_id'])
                disenchant_id = int(row['disenchant_id'])
            except Exception as exc:
                raise SystemExit(f'invalid cache row {row!r}: {exc}')
            source = (row.get('source') or 'SeedLegacy').strip()
            if source not in VALID_SOURCES:
                raise SystemExit(f'invalid DE provenance source item_id={item_id}: {source!r}')
            if item_id <= 0 or disenchant_id < 0:
                raise SystemExit(f'invalid cache values item_id={item_id} disenchant_id={disenchant_id}')
            rows.append((item_id, disenchant_id, source))

    dedup: dict[int, tuple[int, str]] = {}
    for item_id, deid, source in rows:
        old = dedup.get(item_id)
        if old is not None and old != (deid, source):
            raise SystemExit(f'conflicting cache entries item_id={item_id}: {old} vs {(deid, source)}')
        dedup[item_id] = (deid, source)

    for blocked in (20406, 20407, 20408):
        if dedup.get(blocked, (-1, ''))[0] != 0:
            raise SystemExit(f'expected regression item {blocked} to have DisenchantID=0')
    if dedup.get(41316, (0, ''))[0] <= 0:
        raise SystemExit('expected known-positive item 41316 to have DisenchantID>0')

    output_path = Path(args.output_rs)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    with output_path.open('w', encoding='utf-8', newline='\n') as f:
        f.write('// AUTO-GENERATED by poc08_de_cache_to_rust_provenance.py. DO NOT EDIT.\n')
        f.write('// Unknown IDs fail closed. Provenance is preserved for risk decisions.\n')
        f.write('// Confidence 3 is reserved for authoritative/empirically validated evidence.\n')
        f.write('fn poc08_exact_disenchant_id(item_id: u32) -> Option<u32> {\n')
        f.write('    match item_id {\n')
        for item_id in sorted(dedup):
            f.write(f'        {item_id} => Some({dedup[item_id][0]}),\n')
        f.write('        _ => None,\n')
        f.write('    }\n')
        f.write('}\n\n')

        f.write("fn poc08_de_source(item_id: u32) -> Option<&'static str> {\n")
        f.write('    match item_id {\n')
        for item_id in sorted(dedup):
            source = dedup[item_id][1]
            f.write(f'        {item_id} => Some("{source}"),\n')
        f.write('        _ => None,\n')
        f.write('    }\n')
        f.write('}\n\n')

        f.write('fn poc08_de_source_confidence(item_id: u32) -> u8 {\n')
        f.write('    match item_id {\n')
        for item_id in sorted(dedup):
            source = dedup[item_id][1]
            f.write(f'        {item_id} => {confidence_for(source)},\n')
        f.write('        _ => 0,\n')
        f.write('    }\n')
        f.write('}\n\n')
        f.write(f'const POC08_DE_CACHE_ENTRIES: usize = {len(dedup)};\n')

    counts = {source: 0 for source in VALID_SOURCES}
    positive_by_source = {source: 0 for source in VALID_SOURCES}
    for deid, source in dedup.values():
        counts[source] += 1
        if deid > 0:
            positive_by_source[source] += 1
    print(
        '[POC08-E-RUST-CACHE] PASS '
        f'entries={len(dedup)} octo={counts["OctoWow"]} capy={counts["CapyDB"]} seed={counts["SeedLegacy"]} '
        f'positive_octo={positive_by_source["OctoWow"]} positive_capy={positive_by_source["CapyDB"]} '
        f'positive_seed={positive_by_source["SeedLegacy"]} authoritative_current=0 output={output_path}'
    )
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
